### ISSUE TITLE
Still Alive?

### ISSUE THREAD

**Issue by paxsonsa** [swift-quic/swift-quic#18]
Hey there, checking in to see if this is still a live project? Not much activity on this forum

**Comment by btoms20** [comment]
Hey @paxsonsa! I've been MIA for a bit but was planning to pick up development again here shortly. Hopefully by Q2 we'll have an MVP to release. 

p.s. if you'd like to contribute or follow along with the upcoming work check out the [dev branch](https://github.com/swift-quic/swift-quic/tree/develop).

**Comment by paxsonsa** [comment]
That's great to hear! Unfortunately, I am already participating in a few other things but I will definitely someone available to test and try things out, which may inevitably lead me to helping out ;)


I saw there is quite the check list! At this point, how functional is the current implementation?
